"""add genres and anime_genres

Revision ID: fcae052ff99a
Revises: 
Create Date: 2026-06-12 22:31:49.049145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcae052ff99a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Uuid(), nullable=False, on_delete='CASCADE'),
    sa.Column('genre_id', sa.Uuid(), nullable=False, on_delete='CASCADE'),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], name=op.f('fk_anime_genres_anime_id_anime')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_anime_genres_genre_id_genres')),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id', name=op.f('pk_anime_genres'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
